modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "ar2"
version = "0.0.0-dev.${project.version}"
displayName = "advanced rocketry VS"
authors = "nextlevel modding"
description = ''''''
logoFile = "logo.png"

[[mods]]
modId = "nlc"
version = "1.0.2"
displayName = "nextlevel core"
authors = "nextlevel modding"
description = '''a modding util for nextlevel modding'''
logoFile = "nlc.png"

[[mods]]
modId = "lumen"
version = "1.0.2"
displayName = "lumen"
authors = "nextlevel modding"
description = '''realistic light and shadow'''
logoFile = "lumen.png"

[[dependencies."ar2"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."ar2"]]
modId = "valkyrienskies"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies."ar2"]]
modId = "radiation"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies."ar2"]]
modId = "nlc"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies."ar2"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
