modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "ar2"
version = "${mod_version}"
displayName = "advanced rocketry 2"
authors = "nextlevel modding"
description = ''''''
logoFile = "logo.png"

[[mods]]
modId = "nlc"
version = "1.0.0"
displayName = "nextlevel core"
authors = "nextlevel modding"
description = ''''''
logoFile = "nlc.png"

[[dependencies."ar2"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."ar2"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
